---
title: "Evolução da COVID-19 por porte dos municípios"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: united
#runtime: shiny
---

<style type="text/css">
.chart-title {
   font-size: 16px;
   font-weight: bold;
}

.value-box .caption {
    font-size: 16px;
}
</style>

```{r global, include=FALSE, echo=FALSE}
library(dplyr, quietly = TRUE)
library(flexdashboard, quietly = TRUE)
library(forcats, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(lubridate, quietly = TRUE)
library(plotly, quietly = TRUE)
library(readr, quietly = TRUE)
library(scales, quietly = TRUE)
library(sf, quietly = TRUE)
library(shiny, quietly = TRUE)

#source("R/utils.R", echo = FALSE)

theme_set(theme_bw())

plot_porte_lines <- function(df, metrica, min_date = "2020-01-03", ...) {
  covid_porte %>%
    filter(data >= ymd(min_date)) %>%
    ggplot(aes(data, {{ metrica }}, col = porte)) +
    geom_line() +
    scale_x_date(date_breaks = "2 months",
                 date_labels = "%b") +
    facet_wrap(~ regiao, nrow = 2) +
    labs(x = "Data", y = "", col = "", ...) +
    theme_bw() +
    theme(legend.position = "bottom")
}

portes <- c("Menor que 10 mil", "10 a 20 mil", "20 a 100 mil", "Acima de 100 mil")

covid_porte <- read_csv2("data/covid_evolucao_porte_municipios.csv") %>%
  mutate(porte = factor(porte, levels = portes))
```

Row
-----------------------------------------------------------------------

### Incidência por porte dos municípios (média móvel para 7 dias)

```{r, fig.height=8}
plot_porte_lines(covid_porte, incidencia_media7) %>%
  ggplotly() %>%
  layout(legend = list(x = 0.75, y = 0.2))
```

Row
-----------------------------------------------------------------------

### Mortalidade por porte dos municípios (média móvel para 7 dias)

```{r, fig.height=8}
plot_porte_lines(covid_porte, mortalidade_media7) %>%
  ggplotly() %>%
  layout(legend = list(x = 0.75, y = 0.2))
```
